### ISSUE TITLE
 Approaching MVVM 

### ISSUE THREAD

**Issue by JonathanCastilloHurtado** [JonathanCastilloHurtado/MVVM_EXAMPLE#2]
wee aqui ya tiene observers  y se actualiza activamente la vista, pero aun no cuento con un modelo de donde obtenga los datos.

**Comment by JonathanCastilloHurtado** [comment]
la rama de la que hablamos por telefono es : MVVM_CON_OBSERVERS
@gerus9

**Comment by gerus9** [comment]
Ya hice un commit arreglando lo que me comentabas 😄 
Sorry por la tardanza, pero ya sabes 

> Lo urgente no deja tiempo para lo importante
